// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQOu1AD8OC_pmKdqG6SmIfp1NSGKFcM4',
    appId: '1:83162653876:web:06490d3ca421daee4a63e1',
    messagingSenderId: '83162653876',
    projectId: 'marhamchatting',
    authDomain: 'marhamchatting.firebaseapp.com',
    storageBucket: 'marhamchatting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YV_S5tqEHO4BKF_UHnAaFYaginak8k0',
    appId: '1:83162653876:android:23f18ef16b746f4b4a63e1',
    messagingSenderId: '83162653876',
    projectId: 'marhamchatting',
    storageBucket: 'marhamchatting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFINA_9eCDJ1S2agNB7_kvJkeAU_wwNvs',
    appId: '1:83162653876:ios:873cd04f66f10fde4a63e1',
    messagingSenderId: '83162653876',
    projectId: 'marhamchatting',
    storageBucket: 'marhamchatting.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFINA_9eCDJ1S2agNB7_kvJkeAU_wwNvs',
    appId: '1:83162653876:ios:9e18b057fd275d684a63e1',
    messagingSenderId: '83162653876',
    projectId: 'marhamchatting',
    storageBucket: 'marhamchatting.appspot.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
